version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: db_psql
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks: 
      - psql

volumes:
  database_postgres:

networks: 
  psql:
    driver: bridge